[project]
name = "production-grade-agentic-system"
version = "0.1.0"
authors = [
    { name="Alaa Wael", email="alaawael1016@gmail.com" }
]
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "colorama>=0.4.6",
    "concurrent-log-handler>=0.9.29",
    "pydantic-settings>=2.15.0",
    "structlog>=26.1.0",
]

# When you are looking for Python packages, consider src/ to be the package root.

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]
